spring.application.name=backend

# Connect to Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-bold-wind-a5axv01w-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_grOB1TlVb0fW
spring.datasource.driver-class-name=org.postgresql.Driver

# Auto-create/update tables from your @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Print SQL to console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 web console (disabled since we are using Neon)
spring.h2.console.enabled=false

logging.level.org.springframework=debug